class GriffeError(Exception): ...
class LoadingError(GriffeError): ...
class NameResolutionError(GriffeError): ...
class AliasResolutionError(GriffeError): ...
class CyclicAliasError(AliasResolutionError): ...
class UnimportableModuleError(LoadingError): ...
class BuiltinModuleError(UnimportableModuleError): ...
class ExtensionError(GriffeError): ...
class ExtensionNotLoadedError(ExtensionError): ...

__all__ = [
    "AliasResolutionError",
    "BuiltinModuleError",
    "CyclicAliasError",
    "ExtensionError",
    "ExtensionNotLoadedError",
    "GriffeError",
    "LoadingError",
    "NameResolutionError",
    "UnimportableModuleError",
]
