include = ["src/**/*.py"]
exclude = ["tests/**", "docs/_build/**", "site/**", "tools/**"]
ignore = [
    "tests/e2e/**",
    "tests/mock_servers/**",
    "docs/_scripts/**",
    "docs/conf.py",
    "src/__init__.py",
]
ownership_marker = "<!-- auto:docstring-builder v1 -->"
dynamic_probes = false
navmap_metadata = true

[packages]
opt_out = []

[packages.summary_verbs]
kgfoundry = "Document"
kgfoundry_common = "Describe"
tools = "Automate"
