include = ["src/**/*.py", "tools/**/*.py"]
exclude = ["tests/**", "docs/_build/**", "site/**"]
ownership_marker = "<!-- auto:docstring-builder v1 -->"
dynamic_probes = false
navmap_metadata = true

[packages]
opt_out = []

[packages.summary_verbs]
kgfoundry = "Document"
kgfoundry_common = "Describe"
tools = "Automate"
