from __future__ import annotations

from collections.abc import Iterable

class DiGraph[NodeT]:
    def __init__(self) -> None: ...
    def add_nodes_from(self, nodes: Iterable[NodeT]) -> None: ...
    def add_edge(self, u_of_edge: NodeT, v_of_edge: NodeT, **attrs: object) -> None: ...
    @property
    def nodes(self) -> Iterable[NodeT]: ...
    def edges(
        self, data: bool = False
    ) -> Iterable[tuple[NodeT, NodeT] | tuple[NodeT, NodeT, object]]: ...
    def has_edge(self, u_of_edge: NodeT, v_of_edge: NodeT) -> bool: ...
