"""Overview of models.

This module bundles models logic for the kgfoundry stack. It groups related helpers so downstream
packages can import a single cohesive namespace. Refer to the functions and classes below for
implementation specifics.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final, Literal

from pydantic import ConfigDict, Field

from kgfoundry_common.pydantic import BaseModel

if TYPE_CHECKING:
    from kgfoundry_common.navmap_types import NavMap

__all__ = ["Chunk", "Doc", "DoctagsAsset", "Id", "LinkAssertion"]

__navmap__: Final[NavMap] = {
    "title": "kgfoundry_common.models",
    "synopsis": "Typed models shared across kgfoundry services",
    "exports": __all__,
    "sections": [
        {
            "id": "public-api",
            "title": "Public API",
            "symbols": ["Id", "Doc", "DoctagsAsset", "Chunk", "LinkAssertion"],
        },
    ],
    "module_meta": {
        "owner": "@kgfoundry-common",
        "stability": "stable",
        "since": "0.1.0",
    },
    "symbols": {
        "Id": {
            "owner": "@kgfoundry-common",
            "stability": "stable",
            "since": "0.1.0",
        },
        "Doc": {
            "owner": "@kgfoundry-common",
            "stability": "stable",
            "since": "0.1.0",
        },
        "DoctagsAsset": {
            "owner": "@kgfoundry-common",
            "stability": "stable",
            "since": "0.1.0",
        },
        "Chunk": {
            "owner": "@kgfoundry-common",
            "stability": "stable",
            "since": "0.1.0",
        },
        "LinkAssertion": {
            "owner": "@kgfoundry-common",
            "stability": "stable",
            "since": "0.1.0",
        },
    },
}

# [nav:anchor Id]
type Id = str


# [nav:anchor Doc]
class Doc(BaseModel):
    """Document model representing academic papers and publications.

    Pydantic model for representing document metadata including identifiers
    (OpenAlex, DOI, arXiv, PMCID), bibliographic information (title, authors,
    publication date), and content references (PDF URI, content hash).

    Parameters
    ----------
    id : Id
        Unique document identifier (URN or other unique string).
    openalex_id : str | None, optional
        OpenAlex work identifier. Defaults to None.
    doi : str | None, optional
        Digital Object Identifier (DOI). Defaults to None.
    arxiv_id : str | None, optional
        arXiv preprint identifier. Defaults to None.
    pmcid : str | None, optional
        PubMed Central identifier. Defaults to None.
    title : str, optional
        Document title. Defaults to empty string.
    authors : list[str], optional
        List of author names. Defaults to empty list.
    pub_date : str | None, optional
        Publication date string. Defaults to None.
    license : str | None, optional
        License identifier (e.g., "CC-BY"). Defaults to None.
    language : str | None, optional
        Language code (e.g., "en"). Defaults to "en".
    pdf_uri : str, optional
        URI or path to PDF file. Defaults to empty string.
    source : str, optional
        Source identifier (e.g., "openalex", "arxiv"). Defaults to "unknown".
    content_hash : str | None, optional
        SHA256 hash of document content for deduplication. Defaults to None.

    Examples
    --------
    >>> from pathlib import Path
    >>> from kgfoundry_common.schema_helpers import assert_model_roundtrip
    >>> example_path = (
    ...     Path(__file__).parent.parent.parent / "schema" / "examples" / "models" / "doc.v1.json"
    ... )
    >>> assert_model_roundtrip(Doc, example_path)
    """

    model_config = ConfigDict(extra="forbid")

    id: Id
    openalex_id: str | None = None
    doi: str | None = None
    arxiv_id: str | None = None
    pmcid: str | None = None
    title: str = ""
    authors: list[str] = Field(default_factory=list)
    pub_date: str | None = None
    license: str | None = None
    language: str | None = "en"
    pdf_uri: str = ""
    source: str = "unknown"
    content_hash: str | None = None


# [nav:anchor DoctagsAsset]
class DoctagsAsset(BaseModel):
    """Doctags asset model for visual document tags.

    Pydantic model representing visual document tags generated by vision-language
    models (VLMs). Contains references to the doctags file and metadata about
    the model that generated the tags.

    Parameters
    ----------
    doc_id : Id
        Document identifier that this doctags asset belongs to.
    doctags_uri : str
        URI or path to the doctags file (typically JSON or Parquet).
    pages : int
        Number of pages in the document.
    vlm_model : str
        Vision-language model identifier used to generate tags.
    vlm_revision : str
        Model revision or version identifier.
    avg_logprob : float | None, optional
        Average log probability score from the VLM. Defaults to None.
    """

    doc_id: Id
    doctags_uri: str
    pages: int
    vlm_model: str
    vlm_revision: str
    avg_logprob: float | None = None


# [nav:anchor Chunk]
class Chunk(BaseModel):
    """Document chunk model for text segmentation.

    Pydantic model representing a contiguous segment of text from a document.
    Contains character offsets, token counts, and references to doctags spans
    for visual document tags.

    Parameters
    ----------
    id : Id
        Unique chunk identifier.
    doc_id : Id
        Document identifier that this chunk belongs to.
    section : str | None
        Section name or identifier within the document.
    start_char : int
        Start character offset in the original document.
    end_char : int
        End character offset in the original document.
    tokens : int
        Number of tokens in the chunk.
    doctags_span : dict[str, int]
        Dictionary mapping doctags page numbers to character offsets.
    """

    id: Id
    doc_id: Id
    section: str | None
    start_char: int
    end_char: int
    tokens: int
    doctags_span: dict[str, int]


# [nav:anchor LinkAssertion]
class LinkAssertion(BaseModel):
    """Link assertion model for knowledge graph connections.

    Pydantic model representing a link between a document chunk and a knowledge
    graph concept. Contains scoring information, decision status, and optional
    evidence spans and feature vectors.

    Parameters
    ----------
    id : Id
        Unique link assertion identifier.
    chunk_id : Id
        Chunk identifier that this link refers to.
    concept_id : Id
        Knowledge graph concept identifier.
    score : float
        Link score or confidence value.
    decision : Literal['link', 'reject', 'uncertain']
        Decision status: 'link' (accepted), 'reject' (rejected), or
        'uncertain' (requires review).
    evidence_span : str | None, optional
        Text span from the chunk that provides evidence for the link.
        Defaults to None.
    features : dict[str, float], optional
        Feature vector dictionary for the link (e.g., embedding distances,
        similarity scores). Defaults to empty dictionary.
    run_id : str
        Run identifier that created this link assertion.
    """

    id: Id
    chunk_id: Id
    concept_id: Id
    score: float
    decision: Literal["link", "reject", "uncertain"]
    evidence_span: str | None = None
    features: dict[str, float] = Field(default_factory=dict)
    run_id: str
