from __future__ import annotations

from collections.abc import Mapping

__all__ = ["LuceneIndexer"]

class LuceneIndexer:
    """Light-weight stub mirroring Pyserini's Lucene indexer API."""

    def __init__(self, index_dir: str, *args: object, **kwargs: object) -> None: ...
    def add(self, doc: object, /, *args: object, **kwargs: object) -> None: ...
    def add_doc_dict(self, doc: Mapping[str, str], /) -> None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
