from __future__ import annotations

class LuceneIndexer:
    """Stub Lucene indexer."""

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add(self, *args: object, **kwargs: object) -> None: ...
    def commit(self) -> None: ...
