from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from msgspec import json as json

class Struct: ...
class UnsetType: ...

UNSET: UnsetType

class ValidationError(Exception): ...
class DecodeError(Exception): ...

def convert(obj: object, *, target_type: type[object]) -> object: ...
def to_builtins(obj: object) -> dict[str, object]: ...
def field(*, default_factory: Callable[[], object]) -> object: ...

class StructsModule(Protocol):
    def replace(self, obj: object, /, **changes: object) -> object: ...

structs: StructsModule
