from __future__ import annotations

from collections.abc import Callable

class Parser:
    """Subset of the AutoAPI parser surface consumed by kgfoundry."""

    def __init__(self) -> None: ...
    def parse(self, node: object) -> object: ...
    def _parse_file(self, file_path: str, condition: Callable[[str], bool]) -> object: ...
    def parse_file(self, file_path: str) -> object: ...
    def parse_file_in_namespace(self, file_path: str, dir_root: str) -> object: ...
