from __future__ import annotations
from typing import Protocol, List, Dict
from kgforge.kgforge_common.models import Doc, DoctagsAsset

class Registry(Protocol):
    def begin_dataset(self, kind: str, run_id: str) -> str: ...
    def commit_dataset(self, dataset_id: str, parquet_root: str, rows: int) -> None: ...
    def rollback_dataset(self, dataset_id: str) -> None: ...

    def insert_run(self, purpose: str, model_id: str | None, revision: str | None, config: dict) -> str: ...
    def close_run(self, run_id: str, success: bool, notes: str | None = None) -> None: ...

    def register_documents(self, docs: List[Doc]) -> None: ...
    def register_doctags(self, assets: List[DoctagsAsset]) -> None: ...
    def emit_event(self, event_name: str, subject_id: str, payload: Dict) -> None: ...
    def incident(self, event: str, subject_id: str, error_class: str, message: str) -> None: ...
