title: Components
nav:
  - index.md
  - Core Foundations:
      - Doc Processing:
          - docling.md
          - { glob: "docling.*.md", sort: { by: filename, direction: asc, type: natural } }
      - Shared Libraries:
          - kgfoundry_common.md
          - { glob: "kgfoundry_common.*.md", sort: { by: filename, direction: asc, type: natural } }
  - Retrieval Stack:
      - Search Services:
          - search_api.md
          - { glob: "search_api.*.md", sort: { by: filename, direction: asc, type: natural } }
          - search_client.md
          - { glob: "search_client.*.md", sort: { by: filename, direction: asc, type: natural } }
      - Embeddings & Vector Stores:
          - embeddings_dense.md
          - embeddings_sparse.md
          - vectorstore_faiss.md
          - { glob: "embeddings_dense.*.md", sort: { by: filename, direction: asc, type: natural } }
          - { glob: "embeddings_sparse.*.md", sort: { by: filename, direction: asc, type: natural } }
          - { glob: "vectorstore_faiss.*.md", sort: { by: filename, direction: asc, type: natural } }
      - Knowledge Linking:
          - linking.md
          - { glob: "linking.*.md", sort: { by: filename, direction: asc, type: natural } }
  - Data & Knowledge Management:
      - download.md
      - { glob: "download.*.md", sort: { by: filename, direction: asc, type: natural } }
      - kg_builder.md
      - { glob: "kg_builder.*.md", sort: { by: filename, direction: asc, type: natural } }
      - registry.md
      - { glob: "registry.*.md", sort: { by: filename, direction: asc, type: natural } }
      - ontology.md
      - { glob: "ontology.*.md", sort: { by: filename, direction: asc, type: natural } }
  - Operations & Observability:
      - orchestration.md
      - { glob: "orchestration.*.md", sort: { by: filename, direction: asc, type: natural } }
      - observability.md
      - { glob: "observability.*.md", sort: { by: filename, direction: asc, type: natural } }

