from __future__ import annotations

class InvalidVersion(Exception):  # noqa: N818 - class name provided by packaging
    ...

class Version:
    def __init__(self, version: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
