"""Top-level package for internal tooling utilities."""

from __future__ import annotations

import logging

from tools._shared import (
    CLI_ENVELOPE_SCHEMA_ID,
    CLI_ENVELOPE_SCHEMA_VERSION,
    CliEnvelope,
    CliEnvelopeBuilder,
    CliErrorEntry,
    CliErrorStatus,
    CliFileResult,
    CliFileStatus,
    CliStatus,
    ProblemDetailsDict,
    SettingsError,
    StructuredLoggerAdapter,
    ToolExecutionError,
    ToolRunObservation,
    ToolRunResult,
    ToolRuntimeSettings,
    ValidationError,
    build_problem_details,
    build_schema_problem_details,
    build_tool_problem_details,
    get_logger,
    get_runtime_settings,
    new_cli_envelope,
    observe_tool_run,
    problem_from_exception,
    render_cli_envelope,
    render_problem,
    require_directory,
    require_file,
    resolve_path,
    run_tool,
    tool_disallowed_problem_details,
    tool_failure_problem_details,
    tool_missing_problem_details,
    tool_timeout_problem_details,
    validate_cli_envelope,
    validate_tools_payload,
    with_fields,
)

logging.getLogger(__name__).addHandler(logging.NullHandler())

__all__ = [
    "CLI_ENVELOPE_SCHEMA_ID",
    "CLI_ENVELOPE_SCHEMA_VERSION",
    "CliEnvelope",
    "CliEnvelopeBuilder",
    "CliErrorEntry",
    "CliErrorStatus",
    "CliFileResult",
    "CliFileStatus",
    "CliStatus",
    "ProblemDetailsDict",
    "SettingsError",
    "StructuredLoggerAdapter",
    "ToolExecutionError",
    "ToolRunObservation",
    "ToolRunResult",
    "ToolRuntimeSettings",
    "ValidationError",
    "build_problem_details",
    "build_schema_problem_details",
    "build_tool_problem_details",
    "get_logger",
    "get_runtime_settings",
    "logging",
    "new_cli_envelope",
    "observe_tool_run",
    "problem_from_exception",
    "render_cli_envelope",
    "render_problem",
    "require_directory",
    "require_file",
    "resolve_path",
    "run_tool",
    "tool_disallowed_problem_details",
    "tool_failure_problem_details",
    "tool_missing_problem_details",
    "tool_timeout_problem_details",
    "validate_cli_envelope",
    "validate_tools_payload",
    "with_fields",
]
