direction: right
docling: "docling" {
  "docling": "docling" { link: "../modules/docling.md" }
  "docling.canonicalizer": "docling.canonicalizer" { link: "../modules/docling.canonicalizer.md" }
  "docling.hybrid": "docling.hybrid" { link: "../modules/docling.hybrid.md" }
  "docling.vlm": "docling.vlm" { link: "../modules/docling.vlm.md" }
}
