direction: right
download: "download" {
  "download": "download" { link: "../modules/download.md" }
  "download.cli": "download.cli" { link: "../modules/download.cli.md" }
  "download.harvester": "download.harvester" { link: "../modules/download.harvester.md" }
}
