direction: right
embeddings_sparse: "embeddings_sparse" {
  "embeddings_sparse": "embeddings_sparse" { link: "../modules/embeddings_sparse.md" }
  "embeddings_sparse.base": "embeddings_sparse.base" { link: "../modules/embeddings_sparse.base.md" }
  "embeddings_sparse.bm25": "embeddings_sparse.bm25" { link: "../modules/embeddings_sparse.bm25.md" }
  "embeddings_sparse.splade": "embeddings_sparse.splade" { link: "../modules/embeddings_sparse.splade.md" }
}
