direction: right
embeddings_dense: "embeddings_dense" {
  "embeddings_dense": "embeddings_dense" { link: "../modules/embeddings_dense.md" }
  "embeddings_dense.base": "embeddings_dense.base" { link: "../modules/embeddings_dense.base.md" }
  "embeddings_dense.qwen3": "embeddings_dense.qwen3" { link: "../modules/embeddings_dense.qwen3.md" }
}
