direction: right
kg_builder: "kg_builder" {
  "kg_builder": "kg_builder" { link: "../modules/kg_builder.md" }
  "kg_builder.mock_kg": "kg_builder.mock_kg" { link: "../modules/kg_builder.mock_kg.md" }
  "kg_builder.neo4j_store": "kg_builder.neo4j_store" { link: "../modules/kg_builder.neo4j_store.md" }
}
