direction: right
observability: "observability" {
  "observability": "observability" { link: "../modules/observability.md" }
  "observability.metrics": "observability.metrics" { link: "../modules/observability.metrics.md" }
}
