direction: right
ontology: "ontology" {
  "ontology": "ontology" { link: "../modules/ontology.md" }
  "ontology.catalog": "ontology.catalog" { link: "../modules/ontology.catalog.md" }
  "ontology.loader": "ontology.loader" { link: "../modules/ontology.loader.md" }
}
