direction: right
opentelemetry_types: "opentelemetry_types" {
  "kgfoundry_common.opentelemetry_types": "kgfoundry_common.opentelemetry_types" { link: "../modules/kgfoundry_common.opentelemetry_types.md" }
}
