direction: right
registry: "registry" {
  "registry": "registry" { link: "../modules/registry.md" }
  "registry.api": "registry.api" { link: "../modules/registry.api.md" }
  "registry.duckdb_helpers": "registry.duckdb_helpers" { link: "../modules/registry.duckdb_helpers.md" }
  "registry.duckdb_registry": "registry.duckdb_registry" { link: "../modules/registry.duckdb_registry.md" }
  "registry.helper": "registry.helper" { link: "../modules/registry.helper.md" }
  "registry.migrate": "registry.migrate" { link: "../modules/registry.migrate.md" }
}
