direction: right
search_client: "search_client" {
  "search_client": "search_client" { link: "../modules/search_client.md" }
  "search_client.client": "search_client.client" { link: "../modules/search_client.client.md" }
}
