direction: right
types: "types" {
  "kgfoundry_common.types": "kgfoundry_common.types" { link: "../modules/kgfoundry_common.types.md" }
  "search_api.types": "search_api.types" { link: "../modules/search_api.types.md" }
}
