direction: right
vectorstore_faiss: "vectorstore_faiss" {
  "vectorstore_faiss": "vectorstore_faiss" { link: "../modules/vectorstore_faiss.md" }
  "vectorstore_faiss.gpu": "vectorstore_faiss.gpu" { link: "../modules/vectorstore_faiss.gpu.md" }
}
